;;; core.lisp - the bottom of the world.
;;;
;;; Everything here is written with only the nine special forms (quote if
;;; lambda set! define begin while let defmacro) and the % intrinsics, because
;;; at this point in the boot there is nothing else. The compiler open-codes
;;; most of these when it sees them in operator position; the definitions here
;;; are what you get when you pass one around as a value.

(in-package lm)

;; ---------------------------------------------------------------- identity
(define (not x) (if x nil t))
(define (eq? a b) (%eq? a b))
(define (null? x) (%null? x))
(define (pair? x) (%cons? x))
(define (atom? x) (if (%cons? x) nil t))
(define (symbol? x) (%symbol? x))
(define (string? x) (%string? x))
(define (vector? x) (%vector? x))
(define (bytes? x) (%bytes? x))
(define (char? x) (%char? x))
(define (fixnum? x) (%fixnum? x))
(define (number? x) (%fixnum? x))
(define (function? x) (%closure? x))
(define (boolean? x) (if (%null? x) t (%eq? x t)))

;; ---------------------------------------------------------------- pairs
(define (cons a d) (%cons a d))
(define (car x) (%car x))
(define (cdr x) (%cdr x))
(define (set-car! p v) (%set-car! p v))
(define (set-cdr! p v) (%set-cdr! p v))
(define (caar x) (%car (%car x)))
(define (cadr x) (%car (%cdr x)))
(define (cdar x) (%cdr (%car x)))
(define (cddr x) (%cdr (%cdr x)))
(define (caddr x) (%car (%cdr (%cdr x))))
(define (cdddr x) (%cdr (%cdr (%cdr x))))
(define (cadddr x) (%car (%cdr (%cdr (%cdr x)))))
(define (caadr x) (%car (%car (%cdr x))))
(define (cdadr x) (%cdr (%car (%cdr x))))
(define (first x) (%car x))
(define (second x) (%car (%cdr x)))
(define (third x) (%car (%cdr (%cdr x))))
(define (rest x) (%cdr x))

;; ---------------------------------------------------------------- numbers
(define (add2 a b) (%+ a b))
(define (sub2 a b) (%- a b))
(define (mul2 a b) (%* a b))

(define (+ . xs)
  (let ((acc 0))
    (while (%cons? xs)
      (set! acc (%+ acc (%car xs)))
      (set! xs (%cdr xs)))
    acc))

(define (- x . xs)
  (if (%null? xs)
      (%- 0 x)
      (let ((acc x))
        (while (%cons? xs)
          (set! acc (%- acc (%car xs)))
          (set! xs (%cdr xs)))
        acc)))

(define (* . xs)
  (let ((acc 1))
    (while (%cons? xs)
      (set! acc (%* acc (%car xs)))
      (set! xs (%cdr xs)))
    acc))

(define (/ x . xs)
  (let ((acc x))
    (while (%cons? xs)
      (set! acc (%/ acc (%car xs)))
      (set! xs (%cdr xs)))
    acc))

(define (chain2 op xs)
  ;; (< a b c) holds when every neighbouring pair does.
  (let ((ok t))
    (while (%cons? (%cdr xs))
      (if (%funcall op (%car xs) (%car (%cdr xs)))
          nil
          (begin (set! ok nil) (set! xs (list (%car xs)))))
      (set! xs (%cdr xs)))
    ok))


;; These comparators are top level functions rather than lambdas written in
;; place, because a lambda in place would build a closure on every single
;; call - and (> n 0) inside a loop is about as hot as code gets.
(define (num-eq a b) (%= a b))
(define (num-lt a b) (%< a b))
(define (num-gt a b) (%> a b))
(define (num-le a b) (%<= a b))
(define (num-ge a b) (%>= a b))

(define (= . xs) (chain2 num-eq xs))
(define (< . xs) (chain2 num-lt xs))
(define (> . xs) (chain2 num-gt xs))
(define (<= . xs) (chain2 num-le xs))
(define (>= . xs) (chain2 num-ge xs))
(define (/= a b) (if (%= a b) nil t))

(define (1+ n) (%+ n 1))
(define (1- n) (%- n 1))
(define (zero? n) (%= n 0))
(define (positive? n) (%> n 0))
(define (negative? n) (%< n 0))
(define (even? n) (%= 0 (%logand n 1)))
(define (odd? n) (%= 1 (%logand n 1)))
(define (abs n) (if (%< n 0) (%- 0 n) n))
(define (neg n) (%- 0 n))
(define (min2 a b) (if (%< a b) a b))
(define (max2 a b) (if (%> a b) a b))
(define (min x . xs)
  (while (%cons? xs)
    (if (%< (%car xs) x) (set! x (%car xs)) nil)
    (set! xs (%cdr xs)))
  x)
(define (max x . xs)
  (while (%cons? xs)
    (if (%> (%car xs) x) (set! x (%car xs)) nil)
    (set! xs (%cdr xs)))
  x)
(define (mod a b) (%mod a b))
(define (rem a b) (%rem a b))
(define (quotient a b) (%/ a b))
(define (remainder a b) (%rem a b))
(define (modulo a b) (%mod a b))
(define (logand . xs)
  (let ((acc -1))
    (while (%cons? xs) (set! acc (%logand acc (%car xs))) (set! xs (%cdr xs)))
    acc))
(define (logior . xs)
  (let ((acc 0))
    (while (%cons? xs) (set! acc (%logior acc (%car xs))) (set! xs (%cdr xs)))
    acc))
(define (logxor . xs)
  (let ((acc 0))
    (while (%cons? xs) (set! acc (%logxor acc (%car xs))) (set! xs (%cdr xs)))
    acc))
(define (lognot n) (%lognot n))
(define (ash n k) (%ash n k))
(define (lsh n k) (%lsh n k))
(define (bit-set? n k) (%= 1 (%logand 1 (%ash n (%- 0 k)))))

(define (expt b e)
  (let ((acc 1))
    (while (%> e 0)
      (set! acc (%* acc b))
      (set! e (%- e 1)))
    acc))

(define (gcd a b)
  (set! a (abs a))
  (set! b (abs b))
  (while (%> b 0)
    (let ((r (%mod a b)))
      (set! a b)
      (set! b r)))
  a)

;; ---------------------------------------------------------------- lists
(define (list . xs) xs)

(define (list* x . xs)
  ;; (list* 1 2 '(3 4)) => (1 2 3 4)
  (if (%null? xs)
      x
      (let ((head (%cons x nil)) (tail nil))
        (set! tail head)
        (while (%cons? (%cdr xs))
          (%set-cdr! tail (%cons (%car xs) nil))
          (set! tail (%cdr tail))
          (set! xs (%cdr xs)))
        (%set-cdr! tail (%car xs))
        head)))

(define (length xs)
  (let ((n 0))
    (while (%cons? xs)
      (set! n (%+ n 1))
      (set! xs (%cdr xs)))
    n))

(define (reverse xs)
  (let ((acc nil))
    (while (%cons? xs)
      (set! acc (%cons (%car xs) acc))
      (set! xs (%cdr xs)))
    acc))

(define (revappend xs tail)
  (while (%cons? xs)
    (set! tail (%cons (%car xs) tail))
    (set! xs (%cdr xs)))
  tail)

(define (append2 a b)
  (if (%null? a) b (revappend (reverse a) b)))

(define (append . ls)
  (if (%null? ls)
      nil
      (let ((acc nil) (r (reverse ls)))
        (set! acc (%car r))
        (set! r (%cdr r))
        (while (%cons? r)
          (set! acc (append2 (%car r) acc))
          (set! r (%cdr r)))
        acc)))

(define (nthcdr n xs)
  (while (%> n 0)
    (set! xs (%cdr xs))
    (set! n (%- n 1)))
  xs)

(define (nth n xs) (%car (nthcdr n xs)))
(define (list-ref xs n) (%car (nthcdr n xs)))
(define (last-pair xs)
  (while (%cons? (%cdr xs)) (set! xs (%cdr xs)))
  xs)
(define (last xs) (%car (last-pair xs)))

(define (list? x)
  (while (%cons? x) (set! x (%cdr x)))
  (%null? x))

(define (memq x xs)
  (let ((r nil))
    (while (%cons? xs)
      (if (%eq? x (%car xs))
          (begin (set! r xs) (set! xs nil))
          (set! xs (%cdr xs))))
    r))

(define (member x xs)
  (let ((r nil))
    (while (%cons? xs)
      (if (equal? x (%car xs))
          (begin (set! r xs) (set! xs nil))
          (set! xs (%cdr xs))))
    r))

(define (assq k al)
  (let ((r nil))
    (while (%cons? al)
      (if (if (%cons? (%car al)) (%eq? k (%car (%car al))) nil)
          (begin (set! r (%car al)) (set! al nil))
          (set! al (%cdr al))))
    r))

(define (assoc k al)
  (let ((r nil))
    (while (%cons? al)
      (if (if (%cons? (%car al)) (equal? k (%car (%car al))) nil)
          (begin (set! r (%car al)) (set! al nil))
          (set! al (%cdr al))))
    r))

(define (map f xs)
  (if (%null? xs)
      nil
      (let ((head (%cons (%funcall f (%car xs)) nil)) (tail nil))
        (set! tail head)
        (set! xs (%cdr xs))
        (while (%cons? xs)
          (%set-cdr! tail (%cons (%funcall f (%car xs)) nil))
          (set! tail (%cdr tail))
          (set! xs (%cdr xs)))
        head)))

(define (mapcar f xs) (map f xs))

(define (map2 f xs ys)
  (if (%null? xs)
      nil
      (let ((head (%cons (%funcall f (%car xs) (%car ys)) nil)) (tail nil))
        (set! tail head)
        (set! xs (%cdr xs))
        (set! ys (%cdr ys))
        (while (if (%cons? xs) (%cons? ys) nil)
          (%set-cdr! tail (%cons (%funcall f (%car xs) (%car ys)) nil))
          (set! tail (%cdr tail))
          (set! xs (%cdr xs))
          (set! ys (%cdr ys)))
        head)))

(define (for-each f xs)
  (while (%cons? xs)
    (%funcall f (%car xs))
    (set! xs (%cdr xs)))
  nil)

(define (append-map f xs)
  (let ((acc nil))
    (while (%cons? xs)
      (set! acc (revappend (%funcall f (%car xs)) acc))
      (set! xs (%cdr xs)))
    (reverse acc)))

(define (filter pred xs)
  (let ((acc nil))
    (while (%cons? xs)
      (if (%funcall pred (%car xs))
          (set! acc (%cons (%car xs) acc))
          nil)
      (set! xs (%cdr xs)))
    (reverse acc)))

(define (remove-if pred xs)
  (filter (lambda (x) (not (%funcall pred x))) xs))

(define (delq x xs)
  (filter (lambda (y) (not (%eq? x y))) xs))

(define (fold f init xs)
  (while (%cons? xs)
    (set! init (%funcall f init (%car xs)))
    (set! xs (%cdr xs)))
  init)

(define (fold-right f init xs)
  (fold (lambda (acc x) (%funcall f x acc)) init (reverse xs)))

(define (reduce f xs)
  (if (%null? xs) nil (fold f (%car xs) (%cdr xs))))

(define (any pred xs)
  (let ((r nil))
    (while (%cons? xs)
      (let ((v (%funcall pred (%car xs))))
        (if v (begin (set! r v) (set! xs nil)) (set! xs (%cdr xs)))))
    r))

(define (every pred xs)
  (let ((r t))
    (while (%cons? xs)
      (if (%funcall pred (%car xs))
          (set! xs (%cdr xs))
          (begin (set! r nil) (set! xs nil))))
    r))

(define (position x xs)
  (let ((i 0) (r nil))
    (while (%cons? xs)
      (if (equal? x (%car xs))
          (begin (set! r i) (set! xs nil))
          (begin (set! i (%+ i 1)) (set! xs (%cdr xs)))))
    r))

(define (list-index pred xs)
  (let ((i 0) (r nil))
    (while (%cons? xs)
      (if (%funcall pred (%car xs))
          (begin (set! r i) (set! xs nil))
          (begin (set! i (%+ i 1)) (set! xs (%cdr xs)))))
    r))

(define (list-copy xs) (revappend (reverse xs) nil))

(define (iota n)
  (let ((acc nil))
    (while (%> n 0)
      (set! n (%- n 1))
      (set! acc (%cons n acc)))
    acc))

(define (make-list n fill)
  (let ((acc nil))
    (while (%> n 0)
      (set! acc (%cons fill acc))
      (set! n (%- n 1)))
    acc))

(define (sort xs less)
  ;; Merge sort, so it is stable and does not recurse on list length.
  (if (%null? (%cdr xs))
      xs
      (let ((runs nil))
        ;; Start with every element as a run of one.
        (while (%cons? xs)
          (set! runs (%cons (%cons (%car xs) nil) runs))
          (set! xs (%cdr xs)))
        (while (%cons? (%cdr runs))
          (let ((merged nil))
            (while (%cons? runs)
              (if (%cons? (%cdr runs))
                  (begin
                    (set! merged (%cons (merge2 (%car runs) (cadr runs) less) merged))
                    (set! runs (%cdr (%cdr runs))))
                  (begin
                    (set! merged (%cons (%car runs) merged))
                    (set! runs nil))))
            (set! runs merged)))
        (%car runs))))

(define (merge2 a b less)
  (let ((acc nil))
    (while (if (%cons? a) (%cons? b) nil)
      (if (%funcall less (%car b) (%car a))
          (begin (set! acc (%cons (%car b) acc)) (set! b (%cdr b)))
          (begin (set! acc (%cons (%car a) acc)) (set! a (%cdr a)))))
    (while (%cons? a)
      (set! acc (%cons (%car a) acc))
      (set! a (%cdr a)))
    (while (%cons? b)
      (set! acc (%cons (%car b) acc))
      (set! b (%cdr b)))
    (reverse acc)))

;; ---------------------------------------------------------------- equality
(define (eqv? a b)
  (if (%eq? a b)
      t
      (if (%float? a)
          (if (%float? b) (%= (%ld32 (%addr-of a)) (%ld32 (%addr-of b))) nil)
          nil)))

(define (equal? a b)
  (if (%eq? a b)
      t
      (if (%cons? a)
          (if (%cons? b)
              (if (equal? (%car a) (%car b)) (equal? (%cdr a) (%cdr b)) nil)
              nil)
          (if (%string? a)
              (if (%string? b) (string=? a b) nil)
              (if (%vector? a)
                  (if (%vector? b) (vector-equal? a b) nil)
                  nil)))))

(define (vector-equal? a b)
  (if (%= (%vector-length a) (%vector-length b))
      (let ((i 0) (n (%vector-length a)) (ok t))
        (while (%< i n)
          (if (equal? (%vector-ref a i) (%vector-ref b i))
              (set! i (%+ i 1))
              (begin (set! ok nil) (set! i n))))
        ok)
      nil))

;; ---------------------------------------------------------------- characters
(define (char->integer c) (%char->int c))
(define (integer->char n) (%int->char n))
(define (char=? a b) (%eq? a b))
(define (char<? a b) (%< (%char->int a) (%char->int b)))
(define (char>? a b) (%> (%char->int a) (%char->int b)))
(define (char-upcase c)
  (let ((n (%char->int c)))
    (if (if (%>= n 97) (%<= n 122) nil) (%int->char (%- n 32)) c)))
(define (char-downcase c)
  (let ((n (%char->int c)))
    (if (if (%>= n 65) (%<= n 90) nil) (%int->char (%+ n 32)) c)))
(define (char-alphabetic? c)
  (let ((n (%char->int c)))
    (if (if (%>= n 65) (%<= n 90) nil)
        t
        (if (%>= n 97) (%<= n 122) nil))))
(define (char-numeric? c)
  (let ((n (%char->int c)))
    (if (%>= n 48) (%<= n 57) nil)))
(define (char-whitespace? c)
  (let ((n (%char->int c)))
    (if (%= n 32) t (if (%= n 10) t (if (%= n 9) t (%= n 13))))))
(define (digit->int c) (%- (%char->int c) 48))

;; ---------------------------------------------------------------- strings
(define (string-length s) (%string-length s))
(define (string-ref s i) (%string-ref s i))
(define (string-set! s i c) (%string-set! s i c))
(define (make-string n) (make-string-n n))

(define (string=? a b)
  (if (%= (%string-length a) (%string-length b))
      (let ((i 0) (n (%string-length a)) (ok t))
        (while (%< i n)
          (if (%eq? (%string-ref a i) (%string-ref b i))
              (set! i (%+ i 1))
              (begin (set! ok nil) (set! i n))))
        ok)
      nil))

(define (string<? a b)
  (let ((i 0) (na (%string-length a)) (nb (%string-length b)) (r nil) (go t))
    (while go
      (if (%>= i na)
          (begin (set! r (%> nb na)) (set! go nil))
          (if (%>= i nb)
              (begin (set! r nil) (set! go nil))
              (let ((ca (%char->int (%string-ref a i)))
                    (cb (%char->int (%string-ref b i))))
                (if (%= ca cb)
                    (set! i (%+ i 1))
                    (begin (set! r (%< ca cb)) (set! go nil)))))))
    r))

(define (substring s from to)
  (let ((n (%- to from)) (out nil) (i 0))
    (set! out (make-string-n n))
    (while (%< i n)
      (%string-set! out i (%string-ref s (%+ from i)))
      (set! i (%+ i 1)))
    out))

(define (string-append . ss)
  (let ((n 0) (rest ss))
    (while (%cons? rest)
      (set! n (%+ n (%string-length (%car rest))))
      (set! rest (%cdr rest)))
    (let ((out (make-string-n n)) (o 0))
      (set! rest ss)
      (while (%cons? rest)
        (let ((s (%car rest)) (i 0))
          (while (%< i (%string-length s))
            (%string-set! out o (%string-ref s i))
            (set! o (%+ o 1))
            (set! i (%+ i 1))))
        (set! rest (%cdr rest)))
      out)))

(define (string->list s)
  (let ((i (%string-length s)) (acc nil))
    (while (%> i 0)
      (set! i (%- i 1))
      (set! acc (%cons (%string-ref s i) acc)))
    acc))

(define (list->string cs)
  (let ((out (make-string-n (length cs))) (i 0))
    (while (%cons? cs)
      (%string-set! out i (%car cs))
      (set! i (%+ i 1))
      (set! cs (%cdr cs)))
    out))

(define (string . cs) (list->string cs))

(define (string-index s c)
  (let ((i 0) (n (%string-length s)) (r nil))
    (while (%< i n)
      (if (%eq? c (%string-ref s i))
          (begin (set! r i) (set! i n))
          (set! i (%+ i 1))))
    r))

(define (string-upcase s) (list->string (map char-upcase (string->list s))))
(define (string-downcase s) (list->string (map char-downcase (string->list s))))

(define (string->symbol s) (intern-string s))
(define (symbol->string s) (%symbol-name s))
(define (intern s) (intern-string s))
(define (symbol-name s) (%symbol-name s))
(define (gensym) (gensym-1))

(define (number->string n)
  (if (%= n 0)
      "0"
      (let ((neg (%< n 0)) (acc nil))
        (if neg (set! n (%- 0 n)) nil)
        (while (%> n 0)
          (set! acc (%cons (%int->char (%+ 48 (%mod n 10))) acc))
          (set! n (%/ n 10)))
        (if neg (set! acc (%cons (%int->char 45) acc)) nil)
        (list->string acc))))

(define (number->hex n)
  (if (%= n 0)
      "0"
      (let ((acc nil) (d 0))
        (while (if (%> n 0) t (%< n 0))
          (set! d (%logand n 15))
          (set! acc (%cons (%int->char (if (%< d 10) (%+ 48 d) (%+ 87 d))) acc))
          (set! n (%lsh n -4)))
        (list->string acc))))

(define (string->number s)
  (let ((cs (string->list s)) (neg nil) (acc 0) (ok nil))
    (if (%cons? cs)
        (if (%eq? (%car cs) #\-)
            (begin (set! neg t) (set! cs (%cdr cs)))
            (if (%eq? (%car cs) #\+) (set! cs (%cdr cs)) nil))
        nil)
    (while (%cons? cs)
      (if (char-numeric? (%car cs))
          (begin
            (set! ok t)
            (set! acc (%+ (%* acc 10) (digit->int (%car cs))))
            (set! cs (%cdr cs)))
          (begin (set! ok nil) (set! cs nil))))
    (if ok (if neg (%- 0 acc) acc) nil)))

;; ---------------------------------------------------------------- vectors
(define (make-vector n . fill)
  (make-vector-n n (if (%cons? fill) (%car fill) nil)))
(define (vector . xs) (list->vector xs))
(define (vector-length v) (%vector-length v))
(define (vector-ref v i) (%vector-ref v i))
(define (vector-set! v i x) (%vector-set! v i x))

(define (list->vector xs)
  (let ((v (make-vector-n (length xs) nil)) (i 0))
    (while (%cons? xs)
      (%vector-set! v i (%car xs))
      (set! i (%+ i 1))
      (set! xs (%cdr xs)))
    v))

(define (vector->list v)
  (let ((i (%vector-length v)) (acc nil))
    (while (%> i 0)
      (set! i (%- i 1))
      (set! acc (%cons (%vector-ref v i) acc)))
    acc))

(define (vector-fill! v x)
  (let ((i 0) (n (%vector-length v)))
    (while (%< i n)
      (%vector-set! v i x)
      (set! i (%+ i 1)))
    v))

(define (vector-map f v) (list->vector (map f (vector->list v))))

(define (vector-grow v n)
  (let ((out (make-vector-n n nil)) (i 0) (m (%vector-length v)))
    (while (%< i m)
      (%vector-set! out i (%vector-ref v i))
      (set! i (%+ i 1)))
    out))

;; ---------------------------------------------------------------- bytes
(define (make-bytes n) (make-bytes-n n))
(define (bytes-length b) (%bytes-length b))
(define (bytes-ref b i) (%bytes-ref b i))
(define (bytes-set! b i v) (%bytes-set! b i v))

;; ---------------------------------------------------------------- symbols
(define (symbol-value s) (%symbol-value s))
(define (set-symbol-value! s v) (%set-symbol-value! s v))
(define (symbol-function s) (%symbol-function s))
(define (set-symbol-function! s v) (%set-symbol-function! s v))
(define (symbol-plist s) (%symbol-plist s))

(define (get sym key)
  (let ((p (%symbol-plist sym)) (r nil))
    (while (%cons? p)
      (if (%eq? (%car p) key)
          (begin (set! r (cadr p)) (set! p nil))
          (set! p (%cdr p))))
    r))

(define (put sym key val)
  (let ((p (%symbol-plist sym)) (done nil))
    (while (%cons? p)
      (if (%eq? (%car p) key)
          (begin (%set-car! (%cdr p) val) (set! done t) (set! p nil))
          (set! p (%cdr p))))
    (if done
        val
        (begin
          (%set-symbol-plist! sym (%cons key (%cons val (%symbol-plist sym))))
          val))))

;; ---------------------------------------------------------------- functions
(define (apply f args) (apply-list f args))
(define (funcall f . args) (apply-list f args))
(define (identity x) x)
(define (compose f g) (lambda (x) (%funcall f (%funcall g x))))
(define (constantly x) (lambda () x))

;; Output lives in print.lisp for the machine and in hostio.lisp for the
;; forge: the two write to very different places, and neither belongs here.
